Restaurant page, project on JS part of the Curriculum
Abdoulaye-Thespy/Restaurant-Page pull request #1
Opened 2020-09-16 17:54 UTC by Abdoulaye-Thespy

Here we used Webpack bundler to create a Restaurant page with multiple JavaScript files.
Table navigation is used to switch between contents.

2020-09-16 18:34 UTC, lekegitrepo requested changes
## Status: Request changes :recycle:
### Hi Team :clap: :clap:
#### Good job so far :muscle: you have done a good job, however, you need to fix the linter errors and implement some missing requirement and indicated in my comments below.

- **_Fix the linter errors_**

**_Check below for the details of the requirements :point_down:_**

#### _Reviewed by Temitayo Adeleke._

2020-09-16 18:34 UTC, lekegitrepo commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
- **_Commands like `build`, `development` should be in `package.json` inside \`scripts'. Here is a basic example ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/scripts_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622983/))_**

```javascript
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```

2020-09-16 18:34 UTC, lekegitrepo commented on README.md
> +## Project descipription
- **_Correct the typo error_**

2020-09-16 18:34 UTC, lekegitrepo commented on README.md
> +- We have have an an app where the famous game Tic tac toe can be played using Vanilla javascript.
- **_Update the Readme with relevant information about the current project._**

2020-09-16 18:34 UTC, lekegitrepo commented on src/index.js
> +  menuBot.style.color = '#fff';
- **_Keep all the styling logic in CSS files_**

2020-09-17 09:09 UTC, trekab requested changes
### Changes Required! :recycle: 
Hi @Abdoulaye-Thespy, well done implementing the requested changes. You have a few changes to make before moving forward though. These are:
- [ ] Necessary run common commands like `build`, `development` should be in `package.json` inside \`scripts'. This part is empty in your `package.json` file ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/scripts_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622983/))
- [ ] Much as you have done a nice job customizing your `README.md` file, it could use some more improvements. Consider adding your app's screenshot to the `README.md` file. This would make your repository look more professional and encourage visitors to check out your app. Feel free to use [this template](https://github.com/microverseinc/readme-template)

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2020-09-17 17:09 UTC, Oghenebrume50 approved these changes
### APPROVED

Hi @Abdoulaye-Thespy you have done really well, kudos on making changes this looks good to me, please merge and move on **This is approved**

**Raphael Noriode** :mask: STAY_SAFE

2020-11-14 07:05 UTC, merged